"""add_deal_type_to_accounts

Revision ID: 188fe591b9f2
Revises: 8d1ad9032874
Create Date: 2026-02-23 10:38:21.491381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188fe591b9f2'
down_revision: Union[str, Sequence[str], None] = '8d1ad9032874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('deal_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'deal_type')
    # ### end Alembic commands ###
