"""add_watchlist_sync_tables_and_has_new_calls

Revision ID: 845ed44bde5d
Revises: ca10a31311e5
Create Date: 2026-03-13 20:35:41.060941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845ed44bde5d'
down_revision: Union[str, Sequence[str], None] = 'ca10a31311e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tam_accounts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=False),
    sa.Column('account_owner', sa.Text(), nullable=True),
    sa.Column('business_sub_region', sa.Text(), nullable=True),
    sa.Column('business_structure', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name')
    )
    op.create_table('sync_jobs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('total_accounts', sa.Integer(), nullable=False),
    sa.Column('n8n_calls_made', sa.Integer(), nullable=True),
    sa.Column('n8n_calls_succeeded', sa.Integer(), nullable=True),
    sa.Column('n8n_calls_failed', sa.Integer(), nullable=True),
    sa.Column('new_calls_found', sa.Integer(), nullable=True),
    sa.Column('calls_imported', sa.Integer(), nullable=True),
    sa.Column('calls_skipped', sa.Integer(), nullable=True),
    sa.Column('n8n_phase_seconds', sa.Float(), nullable=True),
    sa.Column('scan_phase_seconds', sa.Float(), nullable=True),
    sa.Column('total_seconds', sa.Float(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_jobs_status', 'sync_jobs', ['status', 'started_at'], unique=False)
    op.create_table('sync_account_results',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('sync_job_id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=False),
    sa.Column('n8n_status', sa.Text(), nullable=True),
    sa.Column('n8n_calls_found', sa.Integer(), nullable=True),
    sa.Column('n8n_calls_processed', sa.Integer(), nullable=True),
    sa.Column('n8n_files_created', sa.Integer(), nullable=True),
    sa.Column('n8n_response', sa.Text(), nullable=True),
    sa.Column('n8n_error', sa.Text(), nullable=True),
    sa.Column('n8n_duration_seconds', sa.Float(), nullable=True),
    sa.Column('import_status', sa.Text(), nullable=True),
    sa.Column('new_files_found', sa.Integer(), nullable=True),
    sa.Column('calls_imported', sa.Integer(), nullable=True),
    sa.Column('calls_skipped', sa.Integer(), nullable=True),
    sa.Column('import_error', sa.Text(), nullable=True),
    sa.Column('has_new_data', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_results_account', 'sync_account_results', ['account_id'], unique=False)
    op.create_index('ix_sync_results_job', 'sync_account_results', ['sync_job_id'], unique=False)
    op.create_table('watchlist_accounts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('sf_account_name', sa.Text(), nullable=False),
    sa.Column('added_by', sa.Text(), nullable=True),
    sa.Column('added_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_watchlist_account')
    )
    op.create_index('ix_watchlist_account', 'watchlist_accounts', ['account_id'], unique=False)
    op.add_column('accounts', sa.Column('has_new_calls', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'has_new_calls')
    op.drop_index('ix_watchlist_account', table_name='watchlist_accounts')
    op.drop_table('watchlist_accounts')
    op.drop_index('ix_sync_results_job', table_name='sync_account_results')
    op.drop_index('ix_sync_results_account', table_name='sync_account_results')
    op.drop_table('sync_account_results')
    op.drop_index('ix_sync_jobs_status', table_name='sync_jobs')
    op.drop_table('sync_jobs')
    op.drop_table('tam_accounts')
    # ### end Alembic commands ###
