"""initial schema

Revision ID: 8d1ad9032874
Revises: 
Create Date: 2026-02-22 22:36:18.895682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1ad9032874'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=False),
    sa.Column('mrr_estimate', sa.Float(), nullable=True),
    sa.Column('ic_forecast_category', sa.Text(), nullable=True),
    sa.Column('team_lead', sa.Text(), nullable=True),
    sa.Column('ae_owner', sa.Text(), nullable=True),
    sa.Column('team_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calibration_logs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('calibration_date', sa.Text(), nullable=False),
    sa.Column('config_version', sa.Text(), nullable=False),
    sa.Column('config_previous_version', sa.Text(), nullable=True),
    sa.Column('feedback_items_reviewed', sa.Integer(), nullable=True),
    sa.Column('agent_prompt_changes', sa.Text(), nullable=True),
    sa.Column('config_changes', sa.Text(), nullable=True),
    sa.Column('stage_weight_changes', sa.Text(), nullable=True),
    sa.Column('golden_test_results', sa.Text(), nullable=True),
    sa.Column('tl_agreement_rates', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('last_message_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('calibration_config_version', sa.Text(), nullable=True),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='uq_prompt_version')
    )
    op.create_index('ix_prompt_active', 'prompt_versions', ['agent_id', 'is_active'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Text(), nullable=True),
    sa.Column('page_name', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_events_type_date', 'usage_events', ['event_type', 'created_at'], unique=False)
    op.create_index('ix_usage_events_user', 'usage_events', ['user_name', 'created_at'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('transcript_ids', sa.Text(), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=True),
    sa.Column('total_output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('model_versions', sa.Text(), nullable=True),
    sa.Column('prompt_config_version', sa.Text(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_runs_account', 'analysis_runs', ['account_id', 'started_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_session', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('coaching_entries',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('rep_name', sa.Text(), nullable=False),
    sa.Column('coach_name', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=False),
    sa.Column('coaching_date', sa.Text(), nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=False),
    sa.Column('dimension_score_at_time', sa.Integer(), nullable=True),
    sa.Column('health_score_at_time', sa.Integer(), nullable=True),
    sa.Column('incorporated', sa.Integer(), nullable=True),
    sa.Column('incorporated_at', sa.Text(), nullable=True),
    sa.Column('incorporated_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_coaching_entries_account', 'coaching_entries', ['account_id', 'dimension'], unique=False)
    op.create_index('ix_coaching_entries_rep', 'coaching_entries', ['rep_name', 'coaching_date'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('call_date', sa.Text(), nullable=False),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('preprocessed_text', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('upload_source', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcripts_account_date', 'transcripts', ['account_id', 'call_date'], unique=False)
    op.create_table('user_action_logs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('action_detail', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Text(), nullable=True),
    sa.Column('account_name', sa.Text(), nullable=True),
    sa.Column('page_name', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_logs_account', 'user_action_logs', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_action_logs_type_date', 'user_action_logs', ['action_type', 'created_at'], unique=False)
    op.create_index('ix_action_logs_user_date', 'user_action_logs', ['user_name', 'created_at'], unique=False)
    op.create_table('agent_analyses',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('analysis_run_id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('transcript_count_analyzed', sa.Integer(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence_overall', sa.Float(), nullable=True),
    sa.Column('confidence_rationale', sa.Text(), nullable=True),
    sa.Column('data_gaps', sa.Text(), nullable=True),
    sa.Column('sparse_data_flag', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_analyses_account_agent', 'agent_analyses', ['account_id', 'agent_id', 'created_at'], unique=False)
    op.create_index('ix_agent_analyses_run', 'agent_analyses', ['analysis_run_id'], unique=False)
    op.create_table('deal_assessments',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('analysis_run_id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('deal_memo', sa.Text(), nullable=False),
    sa.Column('contradiction_map', sa.Text(), nullable=True),
    sa.Column('inferred_stage', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.Text(), nullable=False),
    sa.Column('stage_confidence', sa.Float(), nullable=False),
    sa.Column('stage_reasoning', sa.Text(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('health_breakdown', sa.Text(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('confidence_rationale', sa.Text(), nullable=True),
    sa.Column('key_unknowns', sa.Text(), nullable=True),
    sa.Column('momentum_direction', sa.Text(), nullable=False),
    sa.Column('momentum_trend', sa.Text(), nullable=True),
    sa.Column('ai_forecast_category', sa.Text(), nullable=False),
    sa.Column('forecast_confidence', sa.Float(), nullable=True),
    sa.Column('forecast_rationale', sa.Text(), nullable=True),
    sa.Column('top_positive_signals', sa.Text(), nullable=True),
    sa.Column('top_risks', sa.Text(), nullable=True),
    sa.Column('recommended_actions', sa.Text(), nullable=True),
    sa.Column('divergence_flag', sa.Integer(), nullable=True),
    sa.Column('divergence_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', name='uq_deal_assessment_run')
    )
    op.create_index('ix_deal_assessments_account', 'deal_assessments', ['account_id', 'created_at'], unique=False)
    op.create_table('score_feedback',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('account_id', sa.Text(), nullable=False),
    sa.Column('deal_assessment_id', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('feedback_date', sa.Text(), nullable=False),
    sa.Column('health_score_at_time', sa.Integer(), nullable=False),
    sa.Column('disagreement_direction', sa.Text(), nullable=False),
    sa.Column('reason_category', sa.Text(), nullable=False),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('off_channel_activity', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['deal_assessment_id'], ['deal_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_score_feedback_account', 'score_feedback', ['account_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_score_feedback_account', table_name='score_feedback')
    op.drop_table('score_feedback')
    op.drop_index('ix_deal_assessments_account', table_name='deal_assessments')
    op.drop_table('deal_assessments')
    op.drop_index('ix_agent_analyses_run', table_name='agent_analyses')
    op.drop_index('ix_agent_analyses_account_agent', table_name='agent_analyses')
    op.drop_table('agent_analyses')
    op.drop_index('ix_action_logs_user_date', table_name='user_action_logs')
    op.drop_index('ix_action_logs_type_date', table_name='user_action_logs')
    op.drop_index('ix_action_logs_account', table_name='user_action_logs')
    op.drop_table('user_action_logs')
    op.drop_index('ix_transcripts_account_date', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('ix_coaching_entries_rep', table_name='coaching_entries')
    op.drop_index('ix_coaching_entries_account', table_name='coaching_entries')
    op.drop_table('coaching_entries')
    op.drop_index('ix_chat_messages_session', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_analysis_runs_account', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index('ix_usage_events_user', table_name='usage_events')
    op.drop_index('ix_usage_events_type_date', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index('ix_prompt_active', table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_table('chat_sessions')
    op.drop_table('calibration_logs')
    op.drop_table('accounts')
    # ### end Alembic commands ###
